a=int(input("Enter the value"))
b=int(input("Enter the value"))
c=int(input("Enter the value"))
print("Values are:",a,b,c)
print('------------------------------')
num=list(map(int,input().split()))
print(num)
